title: kiwiFella github projects
description: > # this means to ignore newlines until "baseurl:"
  PHP developer with 20 years experience located in Wellington New Zealand. I have worked for 
  both a SaaS product and a digital agency. I have experience with Silverstripe & Wordpress 
  CMS platforms and have 8+ years experience working with PHP MVC frameworks (cakePHP & Laravel). 
permalink: ':title/'
baseurl: ""   #"/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Brendon Baker # add your name
author-img: me-5.png # add your photo
about-author: My projects for learning & development. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kiwiFella # add your Github handle
social-linkedin: choice-as # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
